# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Matthew Berger
email: matthew.sh.berger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Matthew Berger's academic website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matthewberger.github.io" # the base hostname & protocol for your site

permalink: /teaching/vis/fall2018
permalink: /teaching/vis/fall2019
permalink: /teaching/vis/fall2020
permalink: /teaching/vis/spring2022
permalink: /teaching/vis/spring2023
permalink: /teaching/vis/spring2024
permalink: /teaching/vaml/spring2019
permalink: /teaching/vaml/spring2020
permalink: /teaching/vaml/spring2021
permalink: /teaching/aml/fall2021
permalink: /teaching/aml/fall2022
permalink: /teaching/aml/fall2023
permalink: /teaching/aml/fall2024
permalink: /projects/nvv

plugins:
    - jemoji

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
